import "./App.css";
import Header from "./components/Header";
import Content from "./components/Content";
import Footer from "./components/Footer";

function App() {
  return (
    <>
      <Header />
      <Content text="This is my first React Application!" />
      <Content text="Wish me luck..." />
      <Content text="I think I've got it!" />
      <Content text="REACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACTREACT" />
      <Footer />
    </>
  );
}

export default App;
